%-----------------------------------------------------------------------
% Job saved on 16-Nov-2022 22:43:55 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7487)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.fmri_spec.dir = {'/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/Analysis/Outputfiles/Subject028/LocalizerMemory'};
matlabbatch{1}.spm.stats.fmri_spec.timing.units = 'secs';
matlabbatch{1}.spm.stats.fmri_spec.timing.RT = 2;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = 16;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = 8;
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.scans = {
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,1'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,2'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,3'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,4'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,5'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,6'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,7'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,8'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,9'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,10'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,11'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,12'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,13'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,14'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,15'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,16'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,17'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,18'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,19'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,20'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,21'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,22'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,23'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,24'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,25'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,26'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,27'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,28'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,29'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,30'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,31'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,32'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,33'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,34'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,35'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,36'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,37'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,38'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,39'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,40'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,41'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,42'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,43'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,44'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,45'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,46'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,47'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,48'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,49'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,50'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,51'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,52'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,53'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,54'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,55'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,56'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,57'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,58'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,59'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,60'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,61'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,62'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,63'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,64'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,65'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,66'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,67'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,68'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,69'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,70'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,71'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,72'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,73'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,74'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,75'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,76'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,77'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,78'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,79'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,80'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,81'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,82'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,83'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,84'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,85'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,86'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,87'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,88'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,89'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,90'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,91'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,92'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,93'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,94'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,95'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,96'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,97'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,98'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,99'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,100'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,101'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,102'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,103'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,104'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,105'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,106'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,107'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,108'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,109'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,110'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,111'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,112'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,113'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,114'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,115'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,116'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,117'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,118'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,119'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,120'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,121'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,122'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,123'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,124'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,125'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,126'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,127'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,128'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,129'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,130'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,131'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,132'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,133'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,134'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,135'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,136'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,137'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,138'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,139'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,140'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,141'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,142'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,143'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,144'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,145'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,146'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,147'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,148'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,149'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,150'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,151'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,152'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,153'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,154'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,155'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,156'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,157'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,158'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,159'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,160'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,161'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,162'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,163'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,164'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,165'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,166'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,167'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,168'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,169'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,170'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,171'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,172'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,173'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,174'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,175'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,176'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,177'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,178'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,179'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,180'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,181'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,182'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,183'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,184'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,185'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,186'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,187'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,188'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,189'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,190'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,191'
                                                 '/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/EPI_Data/Subject028/s6LocalizerMemory.nii,192'
                                                 };
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi = {'/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/Analysis/Regressors/Subject028/Subject028_LocalizerMemory_Conditions.mat'};
matlabbatch{1}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {'/Users/linfenghan/Desktop/DVIM_fMRI_Analysis/Analysis/Regressors/Subject028/Subject028_LocalizerMemory_HeadMotionRegressors.mat'};
matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_spec.volt = 1;
matlabbatch{1}.spm.stats.fmri_spec.global = 'None';
matlabbatch{1}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_spec.mask = {''};
matlabbatch{1}.spm.stats.fmri_spec.cvi = 'AR(1)';
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('fMRI model specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
